version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install -g @angular/cli@17
      
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo "Building the Angular application..."
      - ng build -c production 
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'
       